spring.application.name=System

spring.datasource.url=jdbc:postgresql://localhost:5432/system
spring.datasource.username=nilesh
spring.datasource.password=qwert123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=godanilesh59@gmail.com
spring.mail.password=mejimzbmkcjujhgs
spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
