spring.application.name=System

spring.datasource.url=jdbc:postgresql://localhost:5432/system
spring.datasource.username=nilesh
spring.datasource.password=qwert123

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=godanilesh59@gmail.com
spring.mail.password=mejimzbmkcjujhgs
spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.pool=true
spring.mail.properties.mail.smtp.pool.size=10

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
logging.level.org.springframework.data.redis=DEBUG


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.org.springframework.amqp=DEBUG


# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/classroom.courses,https://www.googleapis.com/auth/classroom.rosters,openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.access-type=offline
spring.security.oauth2.client.registration.google.prompt=consent
spring.security.oauth2.client.registration.google.client-name=Google
logging.level.org.springframework.security=DEBUG


# Provider URLs (Spring usually autoconfigures, but we define explicitly)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent


